[project]
name = "busy-time"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = ["pydantic==2.13.5"]

[project.scripts]
busytime = "busytime.main:main"

[tool.pytest.ini_options]
addopts = "--import-mode=importlib"

[tool.basedpyright]
typeCheckingMode = "strict"
# include = ["busytime", "tests"]
